export const WORDS = {
    react: [
        'JSX',
        'props',
        'useState',
        'useEffect',
        'useCallback',
        'useRef',
        'createRef',
        'forwardRef',
        'reconcilliation',
        'Virtual DOM',
        'useLayoutEffect',
        'useContext',
        'React',
        'Redux',
        'actionType',
        'actionCreator',
        'reducer',
        'middleware',
        'selector',
        'React Fiber',
        'useSelector',   
        'useDispatch',
        'useId',
        'useTransition',
        'hook',
        'custom hook',
        'shallow equal',
        'memo',
        'create-react-app',
        'package.json',
        'package.lock.json',
        '.gitignore',
        'webpack',
        'render',
        'rerender',
        'mounting',
        'unmounting',
        'Profiler',
        'useDeferredValue',
        'key',
        'immutability',
        'reselect',
        'redux-thunk',
        'redux-saga',
        'component',
        'high order component',
        'css module',
        'children',
        'store',
        'state',
        'dispatch',
        'subsribe',
        'getState',
        'presentational component',
        'container component',
        'controlled component',
        'uncontrolled component',
        'React.lazy',
        'React.Suspense'
    ]
}